[tool.poetry]
name = "oq-id"
version = "0.1.0"
description = "Authorisation system to ecosystem OQ"
authors = ["rashidiy <bubbless7456@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
