"""init

Revision ID: 000
Revises: 
Create Date: 2024-10-12 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """

    Commands isn't auto generated by Alembic - they have created by rashidiy!

    You need to do code below first
        alembic upgrade head

    """
    for table_name in ('users', 'companies', 'userpermissions'):  # noqax
        op.create_table(
            table_name,
            sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )


def downgrade() -> None:
    for table_name in ('userpermissions', 'users', 'companies'):  # noqa
        op.drop_table(table_name)
